### ISSUE TITLE
GPU floating point operations in dfcc implementation

### ISSUE THREAD

**Issue by ankit7540** [edeprince3/gpu_dfcc#1]
Hello.
I am thinking of purchasing a GPU for specifically using the df-cc using psi4 . Now for choosing an appropriate GPU I need to know : 
i) In the present implementation has mathematical operations in FP32 or FP64.
ii) Can we choose to use FP32 for calculations.

 Any specific suggestions for choosing a GPU. Thank you for doing a nice job for GPU accelerated code.

**Comment by edeprince3** [comment]
At this time, this code uses double precision throughout, and there is no option for single precision.

I have done most testing on NVIDIA Tesla K40c (Kepler).  Performance on GP100 (Pascal) is a few times better than on K40c, but I haven't thoroughly tested that architecture.

**Comment by ankit7540** [comment]
Thank you for the clarification. :-)
